---
openapi: 3.0.3
info:
  title: Auth Service
  description: API for user authentication and authorization
  version: 1.0.0
servers:
  - url: http://localhost:5001
paths:
  /auth/login:
    post:
      summary: User authentication
      requestBody:
        description: Email and password
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              type: object
              properties:
                email:
                  type: string
                  example: "pokemon@gmail.com"
                password:
                  type: string
                  example: "Pokemon2023"
      responses:
        "200":
          description: User authenticated successfully
        "500":
          description: bad input parameter
  /auth/user:
    post:
      summary: User creation
      requestBody:
        description: id, email and password
        required: true
        content:
          application/json:
            schema:
              required:
                - id
                - email
                - password
              type: object
              properties:
                id:
                  type: string
                  example: "FR2023IPOK"
                email:
                  type: string
                  example: "pokemon@gmail.com"
                password:
                  type: string
                  example: "Pokemon2023"
      responses:
        "200":
          description: User Created successfully
        "500":
          description: bad input parameter
