---
openapi: 3.0.0
info:
  title: Authentication Service
  description: This is the authentication service
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
servers:
- url: http://localhost:5001
  description: For local tests
paths:
  /auth/authenticate:
    post:
      summary: user authentication
      description: |
        By passing in the appropriate options, user can authenticate
      requestBody:
        description: mail and password
        content:
          application/json:
            schema:
              required:
              - email
              - password
              type: object
              properties:
                email:
                  type: string
                  example: "mail@gmail.com"
                password:
                  type: string
                  example: "qwerty"
      responses:
        "200":
          description: user authenticated
        "400":
          description: bad input parameter
  /auth/users:
    get:
      summary: create user
      description: |
        By passing in the appropriate options, you can create a user
      requestBody:
        description: id, mail and password
        content:
          application/json:
            schema:
              required:
              - id
              - email
              - password
              type: object
              properties:
                id:
                  type: string
                  example: "121212"
                email:
                  type: string
                  example: "mail@gmail.com"
                password:
                  type: string
                  example: "qwerty"
      responses:
        "200":
          description: user created
        "400":
          description: bad input parameter
